### ISSUE TITLE
Config for security

### ISSUE THREAD

**Issue by HariSeldon23** [KudooCloud/kudoo-shared-components#2]
I'd like to have a `config.json` file. This file will detail all internal settings of Kudoo. Currently I see this being the settings for security. So as an example below for the security role for `admin` it would like the below

```
---
admin:
header:
  settings: 
    - user
    - company
    - timesheet
  menuItem:
    - accountSettings
    - logout
drawer:
  menuItem: 
    - dashboard:
      - widgets:
        - revenueByYear
        - avgPerMonth
        - invoices
        - mostRecentCust
        - mostRecentProj
    - projects:
      - screens:
        - active
        - draft 
        - archived
    - invoices:
      - screens:
        - unpaid
          - sent 
          - draft
        - paid
        - archived
    - timesheets:
      - screens: 
        - myTimesheets
          - active
          - draft
          - archived
        - allTimesheets
          - active
          - draft
          - archived
    - customers: 
      - screens:
        - allCustomers
        - archived
    - workers:
      - allWorkers
      - archived
    - services:
      - active
      - archived
```

Then when we render the `drawer` component, we'll query this `json` file to see which items to show.
Then when we render `header` we'll query this `json` file to see how it renders.
Then when we render the `menu items` from the drawer we'll also use this to see which screens are allowed.

For example if we wanted to add a new user role, we'd only need to add an extra config for the new role to this `json` file and `Kudoo` would automatically work for the new user role without any code changes.
